language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

script: go test -coverprofile=coverage.txt -covermode=atomic -race -v -parallel 4 ./...

after_success:
      - bash <(curl -s https://codecov.io/bash)
